import { test,expect } from '@playwright/test';

test('login, demo navigation, allowlist mutation and reload isolation',async({page})=>{
  const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));
  await page.goto('/login');
  await expect(page.getByRole('heading',{name:'เข้าสู่ระบบ'})).toBeVisible();
  await page.screenshot({path:'test-results/login-desktop.png',fullPage:true,animations:'disabled'});
  await page.getByRole('button',{name:'เปิดโหมดตัวอย่าง'}).click();
  await expect(page.locator('.demo-banner')).toBeVisible();
  await page.screenshot({path:'test-results/dashboard-desktop.png',fullPage:true,animations:'disabled'});
  const nav=page.getByRole('navigation',{name:'เมนูหลัก'});
  const navButtons=nav.getByRole('button');
  const count=await navButtons.count();
  for(let i=0;i<count;i++){await navButtons.nth(i).click();await expect(page.locator('main h1')).toBeVisible();}
  await nav.getByRole('button',{name:'อีเมลที่อนุญาต',exact:true}).click();
  await page.getByRole('button',{name:'เพิ่มอีเมล',exact:true}).click();
  const dialog=page.getByRole('dialog');
  await dialog.locator('input[name="email"]').fill('browser-test@example.com');
  await dialog.getByRole('button',{name:'เพิ่มอีเมล',exact:true}).click();
  await expect(dialog).toBeHidden();
  await expect(page.getByText('browser-test@example.com',{exact:true})).toBeVisible();
  await page.reload();await expect(page.getByRole('button',{name:'เปิดโหมดตัวอย่าง'})).toBeVisible();
  expect(errors).toEqual([]);
});

test('mobile layout, navigation drawer and security page',async({page})=>{
  await page.setViewportSize({width:390,height:844});await page.goto('/login');
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBeTruthy();
  await page.getByRole('button',{name:'เปิดโหมดตัวอย่าง'}).click();
  await page.screenshot({path:'test-results/dashboard-mobile.png',fullPage:true,animations:'disabled'});
  await page.getByRole('button',{name:'เปิดเมนู',exact:true}).click();
  await expect(page.locator('.sidebar')).toHaveClass(/open/);
  await page.getByRole('navigation',{name:'เมนูหลัก'}).getByRole('button',{name:'ความปลอดภัย',exact:true}).click();
  await expect(page.locator('.sidebar')).not.toHaveClass(/open/);
  await expect(page.locator('main h1')).toBeVisible();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBeTruthy();
});

test('demo application, one-time API key, revocation and MFA recovery setup',async({page})=>{
  const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));
  await page.goto('/login');await page.getByRole('button',{name:'เปิดโหมดตัวอย่าง'}).click();
  const nav=page.getByRole('navigation',{name:'เมนูหลัก'});
  await nav.getByRole('button',{name:'แอปพลิเคชัน',exact:true}).click();
  await page.getByRole('button',{name:'เพิ่มแอปพลิเคชัน',exact:true}).click();
  let dialog=page.getByRole('dialog');await dialog.locator('input[name="name"]').fill('Browser test app');
  await dialog.locator('input[name="redirectUri"]').fill('https://browser-test.example.com/callback');
  await dialog.getByRole('button',{name:'เพิ่มแอปพลิเคชัน',exact:true}).click();
  await nav.getByRole('button',{name:'API keys',exact:true}).click();
  await page.getByRole('button',{name:'สร้าง API key',exact:true}).click();
  dialog=page.getByRole('dialog');await dialog.locator('input[name="name"]').fill('Browser test key');
  await dialog.locator('select[name="applicationId"]').selectOption({label:'Browser test app'});
  await dialog.getByRole('button',{name:'สร้าง API key',exact:true}).click();
  await expect(dialog.locator('.secret-key')).toContainText('DEMO_UI_ONLY_');
  await dialog.getByRole('checkbox').check();await dialog.getByRole('button',{name:'บันทึกแล้ว เสร็จสิ้น'}).click();
  const row=page.getByRole('row').filter({hasText:'Browser test key'});
  await row.getByRole('button').last().click();
  await page.getByRole('dialog').getByRole('button',{name:'ยืนยันยกเลิกสิทธิ์'}).click();
  await expect(row).toContainText('เพิกถอน');
  await nav.getByRole('button',{name:'ความปลอดภัย',exact:true}).click();
  await page.getByRole('button',{name:'ปิดใช้งาน',exact:true}).click();
  dialog=page.getByRole('dialog');await dialog.locator('.otp-digits input').first().fill('123456');
  await dialog.getByRole('button',{name:'ยืนยันปิดใช้งาน'}).click();
  await page.getByRole('button',{name:'เปิดใช้งาน',exact:true}).click();
  dialog=page.getByRole('dialog');await expect(dialog.getByRole('img',{name:'QR code สำหรับตั้งค่า Authenticator'})).toBeVisible();
  await expect(dialog.locator('.recovery-codes code')).toHaveCount(8);
  await dialog.getByRole('checkbox').check();await dialog.locator('.otp-digits input').first().fill('123456');
  await dialog.getByRole('button',{name:'ยืนยันและเปิดใช้งาน'}).click();
  await expect(page.getByRole('button',{name:'ปิดใช้งาน',exact:true})).toBeVisible();
  expect(errors).toEqual([]);
});

const ssoParams = new URLSearchParams({ response_type: 'code', client_id: 'b7ab297a-8903-4550-b3cc-c11daed7a824', redirect_uri: 'https://people.example.com/callback', state: 'S'.repeat(43), code_challenge: 'A'.repeat(43), code_challenge_method: 'S256' });
const returnTo = `/api/sso/authorize?${ssoParams}`;
const loginUrl = `/login?${new URLSearchParams({ returnTo, name: 'Untrusted application name' })}`;
const contextBody = { application: { name: 'People & HR', origin: 'https://people.example.com' }, returnTo };
const signedIn = { user: { id: 'test-user', name: 'Test User', email: 'member@example.com', role: 'user', totpEnabled: true }, csrfToken: 'test-csrf', requiresMfa: false, mfaMethod: 'totp' };

test('central login shows verified service, keeps target, and blocks unsafe login requests', async ({ page }) => {
  await page.route('**/api/auth/status', route => route.fulfill({ json: { configured: true } }));
  await page.route('**/api/auth/me', route => route.fulfill({ status: 401, json: { error: 'Login required' } }));
  await page.route('**/api/sso/login-context?**', route => route.fulfill({ json: contextBody }));
  await page.goto(loginUrl);
  await expect(page).toHaveTitle('CUSA SSO');
  await expect(page.locator('.auth-application')).toContainText('People & HR');
  await expect(page.getByText('Untrusted application name')).toHaveCount(0);
  await expect(page.getByRole('button', { name: 'เปิดโหมดตัวอย่าง' })).toHaveCount(0);
  await expect(page.getByRole('link', { name: 'ดำเนินการต่อด้วย Google' })).toHaveAttribute('href', `/api/auth/google/start?${new URLSearchParams({ returnTo })}`);
  await page.screenshot({ path: 'test-results/service-login-desktop.png', fullPage: true, animations: 'disabled' });
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy();
  await page.screenshot({ path: 'test-results/service-login-mobile.png', fullPage: true, animations: 'disabled' });
  await page.goto('/login?returnTo=https%3A%2F%2Fattacker.example');
  await expect(page.getByRole('heading', { name: 'ไม่สามารถเข้าสู่ระบบได้' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'ดำเนินการต่อด้วย Google' })).toHaveCount(0);
});

test('MFA resumes the original service and existing sessions show continuation without admin loading', async ({ page }) => {
  let verified = false; const adminRequests: string[] = [];
  page.on('request', req => { if (req.url().includes('/api/admin/')) adminRequests.push(req.url()); });
  await page.route('**/api/auth/status', route => route.fulfill({ json: { configured: true } }));
  await page.route('**/api/auth/me', route => route.fulfill({ json: { ...signedIn, requiresMfa: !verified } }));
  await page.route('**/api/sso/login-context?**', route => route.fulfill({ json: contextBody }));
  await page.route('**/api/auth/totp/verify', async route => {
    expect(route.request().postDataJSON()).toEqual({ code: '123456' });
    expect(route.request().headers()['x-csrf-token']).toBe('test-csrf');
    verified = true; await route.fulfill({ json: { ok: true } });
  });
  await page.route('**/api/sso/authorize?**', route => route.fulfill({ contentType: 'text/html', body: '<h1>Returned to authorization</h1>' }));
  await page.goto(loginUrl);
  await expect(page.getByRole('heading', { name: 'ยืนยันว่าเป็นคุณ' })).toBeVisible();
  await expect(page.locator('.auth-application')).toContainText('People & HR');
  await page.locator('.otp-digits input').first().fill('123456');
  await page.getByRole('button', { name: 'ยืนยันและเข้าสู่ระบบ' }).click();
  await expect(page.getByRole('heading', { name: 'Returned to authorization' })).toBeVisible();
  await page.goto(loginUrl);
  await expect(page.getByRole('heading', { name: 'พร้อมเข้าใช้งาน' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'ดำเนินการต่อ', exact: true })).toHaveAttribute('href', returnTo);
  expect(adminRequests).toEqual([]);
});

test('user profile and custom service roles support multiple assignments without leaking into other services', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  await page.goto('/login'); await page.getByRole('button', { name: 'เปิดโหมดตัวอย่าง' }).click();
  const nav = page.getByRole('navigation', { name: 'เมนูหลัก' });
  await nav.getByRole('button', { name: /^ผู้ใช้งาน/ }).click();
  await page.getByRole('button', { name: 'รายละเอียด kittipong@example.com', exact: true }).click();
  let dialog = page.getByRole('dialog');
  await dialog.getByLabel('ชื่อ', { exact: true }).fill('สมชาย');
  await dialog.getByLabel('นามสกุล', { exact: true }).fill('ใจดี');
  await dialog.getByRole('button', { name: 'บันทึกข้อมูล' }).click();
  await expect(page.getByRole('row').filter({ hasText: 'kittipong@example.com' })).toContainText('สมชาย ใจดี');
  await nav.getByRole('button', { name: 'สิทธิ์แต่ละ Service', exact: true }).click();
  await page.getByRole('button', { name: 'เพิ่ม Role', exact: true }).click();
  dialog = page.getByRole('dialog');
  await dialog.getByLabel('รหัส Role').fill('approver'); await dialog.getByLabel('ชื่อ Role').fill('ผู้อนุมัติ');
  await dialog.getByRole('button', { name: 'บันทึก', exact: true }).click();
  await page.getByRole('button', { name: 'เพิ่มสมาชิก', exact: true }).click();
  dialog = page.getByRole('dialog');
  await dialog.getByRole('combobox', { name: 'ผู้ใช้', exact: true }).selectOption('user-3');
  await dialog.getByLabel('หน่วยงานใน Service นี้').fill('ฝ่ายการเงิน');
  await dialog.getByRole('checkbox', { name: /ผู้อนุมัติ/ }).check();
  await dialog.getByRole('checkbox', { name: /ผู้ดูข้อมูล/ }).check();
  await dialog.getByRole('button', { name: 'บันทึก', exact: true }).click();
  let row = page.getByRole('row').filter({ hasText: 'kittipong@example.com' });
  await expect(row).toContainText('ฝ่ายการเงิน'); await expect(row).toContainText('approver'); await expect(row).toContainText('viewer');
  await page.screenshot({ path: 'test-results/service-access-desktop.png', fullPage: true, animations: 'disabled' });
  await page.getByRole('combobox', { name: 'Service', exact: true }).selectOption('app-2');
  await expect(page.getByRole('heading', { name: 'Role ของ People & HR' })).toBeVisible();
  await expect(page.getByRole('row').filter({ hasText: 'kittipong@example.com' })).toHaveCount(0);
  await expect(page.getByRole('button', { name: 'แก้ไข Role approver' })).toHaveCount(0);
  await page.getByRole('combobox', { name: 'Service', exact: true }).selectOption('app-1');
  await page.getByRole('button', { name: 'ลบ Role approver' }).click();
  await page.getByRole('dialog').getByRole('button', { name: 'ยืนยัน', exact: true }).click();
  await expect(page.getByRole('dialog').getByRole('alert')).toContainText('ยังมีผู้ใช้');
  await page.getByRole('dialog').getByRole('button', { name: 'ยกเลิก', exact: true }).click();
  await page.getByRole('button', { name: 'ถอนสมาชิก kittipong@example.com' }).click();
  await page.getByRole('dialog').getByRole('button', { name: 'ยืนยัน', exact: true }).click();
  await expect(page.getByRole('row').filter({ hasText: 'kittipong@example.com' })).toHaveCount(0);
  await page.getByRole('button', { name: 'ลบ Role approver' }).click();
  await page.getByRole('dialog').getByRole('button', { name: 'ยืนยัน', exact: true }).click();
  await expect(page.getByRole('button', { name: 'แก้ไข Role approver' })).toHaveCount(0);
  expect(errors).toEqual([]);
});
