import { Router } from 'express';
import * as c from '../controllers/authController.js';
import { requireConfigured,requireSession,requireAuth,requireUnlocked,rateLimit } from '../middleware/security.js';
import { validateBody,codeSchema,recoverySchema } from '../middleware/validation.js';
export const authRouter=Router();
authRouter.get('/status',c.status);
authRouter.get('/me',requireSession,c.me);
authRouter.get('/google/start',requireConfigured,rateLimit('google-start',20,600),c.googleStart);
authRouter.get('/google/callback',requireConfigured,rateLimit('google-callback',30,600),c.googleCallback);
authRouter.use(requireConfigured,requireSession);
authRouter.post('/logout',c.logout);
authRouter.get('/sessions',requireAuth,c.sessions);
authRouter.delete('/sessions/:id',requireAuth,c.revokeSession);
authRouter.use(requireUnlocked);
authRouter.post('/otp/send',rateLimit('otp-send',3,600),c.otpSend);
authRouter.post('/otp/verify',rateLimit('mfa-verify',10,600),validateBody(codeSchema),c.otpVerify);
authRouter.post('/totp/verify',rateLimit('mfa-verify',10,600),validateBody(codeSchema),c.totpVerify);
authRouter.post('/recovery/verify',rateLimit('mfa-verify',10,600),validateBody(recoverySchema),c.recoveryVerify);
authRouter.use(requireAuth);
authRouter.post('/totp/setup',rateLimit('mfa-setup',5,600),c.totpSetup);
authRouter.post('/totp/enable',rateLimit('mfa-verify',10,600),validateBody(codeSchema),c.totpEnable);
authRouter.post('/totp/disable',rateLimit('mfa-verify',10,600),validateBody(codeSchema),c.totpDisable);
authRouter.post('/recovery/regenerate',rateLimit('mfa-verify',10,600),validateBody(codeSchema),c.recoveryRegenerate);
