import * as reset from '../controllers/mfaResetController.js';
import { evidenceCapacity,evidenceUpload } from '../middleware/evidenceUpload.js';
import { Router } from 'express';
import * as c from '../controllers/authController.js';
import * as factors from '../controllers/factorController.js';
import { googleQueueGate } from '../controllers/waitingRoomController.js';
import { requireConfigured,requireSession,requireAuth,requireFullSession,requireUnlocked,rateLimit } from '../middleware/security.js';
import { validateBody,emailCodeSchema,codeSchema,recoverySchema } from '../middleware/validation.js';
export const authRouter=Router();
authRouter.get('/status',c.status);
authRouter.get('/me',requireSession,c.me);
authRouter.get('/google/start',requireConfigured,rateLimit('google-start',20,600),googleQueueGate,c.googleStart);
authRouter.get('/google/callback',requireConfigured,rateLimit('google-callback',30,600),c.googleCallback);
authRouter.use(requireConfigured,requireSession);
authRouter.post('/logout',c.logout);
authRouter.get('/sessions',requireAuth,c.sessions);
authRouter.delete('/sessions',requireAuth,rateLimit('self-session-revoke',5,60),c.revokeOwnSessions);
authRouter.delete('/sessions/:id',requireAuth,c.revokeSession);
authRouter.get('/mfa-reset',reset.own);
authRouter.post('/mfa-reset',rateLimit('mfa-reset',3,86400),evidenceCapacity,evidenceUpload,reset.submit);
authRouter.use(requireUnlocked);
authRouter.get('/factors',requireFullSession,factors.settings);
authRouter.post('/phone/start',requireFullSession,rateLimit('phone-send',3,600),factors.phoneStart);
authRouter.post('/phone/verify',requireFullSession,rateLimit('phone-verify',5,600),factors.phoneVerify);
authRouter.post('/passkeys/authenticate/options',rateLimit('passkey-options',10,600),factors.authenticateOptions);
authRouter.post('/passkeys/authenticate/verify',rateLimit('mfa-verify',10,600),factors.authenticateVerify);
authRouter.post('/line/send',rateLimit('line-send',3,600),factors.lineSend);
authRouter.get('/line/challenges/:id',factors.lineStatus);
authRouter.post('/line/verify',rateLimit('mfa-verify',10,600),factors.lineVerify);
authRouter.post('/otp/send',rateLimit('otp-send',3,600),c.otpSend);
authRouter.post('/otp/verify',rateLimit('mfa-verify',10,600),validateBody(emailCodeSchema),c.otpVerify);
authRouter.post('/totp/verify',rateLimit('mfa-verify',10,600),validateBody(codeSchema),c.totpVerify);
authRouter.post('/recovery/verify',rateLimit('mfa-verify',10,600),validateBody(recoverySchema),c.recoveryVerify);
authRouter.use(requireAuth);
authRouter.post('/passkeys/reauth/options',rateLimit('passkey-options',10,600),factors.reauthenticateOptions);
authRouter.post('/passkeys/reauth/verify',rateLimit('mfa-verify',10,600),factors.reauthenticateVerify);
authRouter.post('/passkeys/register/options',rateLimit('factor-manage',10,600),factors.registerOptions);
authRouter.post('/passkeys/register/verify',rateLimit('factor-manage',10,600),factors.registerVerify);
authRouter.delete('/passkeys/:id',rateLimit('factor-manage',10,600),factors.deletePasskey);
authRouter.post('/line/link',rateLimit('factor-manage',10,600),factors.lineStart);
authRouter.get('/line/callback',rateLimit('factor-manage',10,600),factors.lineCallback);
authRouter.delete('/line/link',rateLimit('factor-manage',10,600),factors.unlinkLine);
authRouter.post('/reauth',rateLimit('mfa-verify',10,600),validateBody(codeSchema),c.reauthenticate);
authRouter.post('/totp/setup',rateLimit('mfa-setup',5,600),c.totpSetup);
authRouter.post('/totp/enable',rateLimit('mfa-verify',10,600),validateBody(codeSchema),c.totpEnable);
authRouter.post('/totp/disable',rateLimit('mfa-verify',10,600),validateBody(codeSchema),c.totpDisable);
authRouter.post('/recovery/regenerate',rateLimit('mfa-verify',10,600),validateBody(codeSchema),c.recoveryRegenerate);
